apiVersion: v1
kind: Service
metadata:
  name: service-two-clusterip
  labels:
    app: service-two
    mode: basic
    category: learning
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 9002
      port: 9002
  selector:
    app: service-two
    mode: basic
    category: learning