apiVersion: v1
kind: Service
metadata:
  name: service-one-clusterip
  labels:
    app: service-one
    mode: basic
    category: learning
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 9001
      port: 9001
  selector:
    app: service-one
    mode: basic
    category: learning