apiVersion: v1
kind: Service
metadata:
  name: service-one-service
  labels:
    app: service-one
    mode: basic
    category: learning
spec:
  type: NodePort
  selector:
    app: service-one
    mode: basic
    category: learning
  ports:
    - port: 7000
      targetPort: 9001
      nodePort: 30901
      protocol: TCP